version: '3'
services:
  db:
    image: mysql/mysql-server:8.0
    network_mode: bridge
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sql
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=sql
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    volumes: 
      - ./db:/var/lib/mysql
      - ./test_data:/mnt/backup
volumes:
  db:
    driver: local
  backup:
    driver: local